version: '3'
services:
  www:
    image: php:apache
    volumes:
      - C:/xampp/htdocs/UASWEB:/var/www/html
    ports:
    - 8085:80
    - 443:443
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db_catering_uas
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8086:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306


